[package]
authors = ["Alex Johnson <alex.kattathra.johnson@gmail.com>", "Albert O'Shea"]
repository = "https://github.com/alex-kattathra-johnson/nu_plugin_ws"
readme = "README.md"
license = "MIT"
name = "nu-plugin-ws"
description = "A Nushell plugin for easily streaming output from websocket endpoints"
version = "1.0.6"
edition = "2024"
autobins = false

[[bin]]
name = "nu_plugin_ws"
path = "src/main.rs"

[[bin]]
name = "nu_ws_live_fixture_server"
path = "src/bin/live_fixture_server.rs"

[dependencies]
nu-plugin = true
nu-protocol = true
serde_json = true
tracing = true
tracing-subscriber = { default-features = false, features = ["fmt"] }
tungstenite = { features = ["native-tls"] }

[dev-dependencies]
nu-plugin-test-support = true
nu-test-support = true

[profile.release]
strip = true
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
